name: 'Wiki Sync'
description: 'Sync a wiki folder with your GitHub Wiki'
inputs:
    username:
        description: 'The username of the repo owner'
        required: true
    access_token:
        description: 'The access token with Repo access. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
        required: true
    wiki_folder:
        description: 'The folder you want to sync the repo with'
        required: false
        default: 'wiki'
    commit_message:
        description: 'A custom commit message to be used'
        required: false
        default: 'action: wiki sync'
    commit_username:
        description: 'The email address to use with the commit'
        required: true
    commit_email:
        description: 'The email address to use when committing'
        required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    USERNAME: ${{ inputs.username }}
    ACCESS_TOKEN: ${{ inputs.access_token }}
    WIKI_FOLDER: ${{ inputs.wiki_folder }}
    COMMIT_MESSAGE: $${{ inputs.commit_message }}